version: "3.8"
services:
  json-server:
    build: ./back
    container_name: json-server_c
    ports:
        - "3000:3000"
        - "4000:4000"
    networks:
      - internal
    volumes:
      - type: bind
        source: ./back/data
        target: /usr/src/app/back/data
    restart: unless-stopped
    command: npm run json-server
  react:
    build: ./front
    ports:
     - "8080:8080"
    container_name: reactjs_c
    networks:
      - internal
    volumes:
      - type: bind
        source: ./front/src
        target: /usr/src/app/front/src
      - type: bind
        source: ./front/public
        target: /usr/src/app/front/public
    restart: unless-stopped
    command: npm run build-serve
networks: 
  internal:
    driver: bridge
